experiment: simplevit-huge-{model.args.patch_size}
batch_size: 32
epochs: 100
output_dir: save
resume: null
save_interval: 10

optimizer:
  type: Adam
  args:
    lr: 3.0e-5

scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 100

model:
  type: SimpleViT
  args:
    image_size: 224
    patch_size: 14
    num_classes: null
    dim: 1280
    depth: 32
    heads: 16
    mlp_dim: 5120
