dataset:
  type: CIFAR10
  train:
    args:
      train: True
      root: /data/baole/cifar10
      download: True
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 256, 256 ]
      - type: RandomCrop
        args:
          size: 224
      - type: RandomHorizontalFlip
      - type: Normalize
        args:
          mean: [ 0.49139968, 0.48215827 ,0.44653124 ]
          std: [ 0.24703233, 0.24348505, 0.26158768 ]
    loader:
      shuffle: True
      num_workers: 16
      pin_memory: True
  test:
    args:
      train: False
      root: /data/baole/cifar10
      download: True
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 224, 224 ]
      - type: Normalize
        args:
          mean: [ 0.49139968, 0.48215827, 0.44653124 ]
          std: [ 0.24703233, 0.24348505, 0.26158768 ]
    loader:
      shuffle: False
      num_workers: 16
      pin_memory: True
