dataset:
  type: ImageNet
  train:
    args:
      root: /data/baole/imagenet
      split: train
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 256, 256 ]
      - type: RandomCrop
        args:
          size: 224
      - type: RandomHorizontalFlip
      - type: Normalize
        args:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
    loader:
      shuffle: True
      num_workers: 16
      pin_memory: True
  test:
    args:
      root: /data/baole/imagenet
      split: val
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 224, 224 ]
      - type: Normalize
        args:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
    loader:
      shuffle: False
      num_workers: 16
      pin_memory: True
