experiment: cifar10_vkd
epochs: 100
output_dir: save
resume: null
save_interval: 10
load_model_path: models/teacher.pt

dataset:
  type: CIFAR10
  train:
    args:
      train: True
      root: ../data/cifar-10 #/data/baole/cifar10
      download: True
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 256, 256 ]
      - type: RandomCrop
        args:
          size: 224
      - type: RandomHorizontalFlip
      - type: Normalize
        args:
          mean: [ 0.49139968, 0.48215827 ,0.44653124 ]
          std: [ 0.24703233, 0.24348505, 0.26158768 ]
    loader:
      batch_size: 64
      shuffle: True
      num_workers: 16
      pin_memory: True
  test:
    args:
      train: False
      root: ../data/cifar-10 #/data/baole/cifar10
      download: True
    transforms:
      - type: ToTensor
      - type: Resize
        args:
          size: [ 224, 224 ]
      - type: Normalize
        args:
          mean: [ 0.49139968, 0.48215827, 0.44653124 ]
          std: [ 0.24703233, 0.24348505, 0.26158768 ]
    loader:
      batch_size: 64
      shuffle: False
      num_workers: 16
      pin_memory: True

teacher_model: 
  type: ViT
  args:
    image_size: 224
    patch_size: 32
    num_classes: 100
    dim: 2048
    depth: 6
    heads: 16
    mlp_dim: 4096
    dropout: 0.1

student_model:
  type: ViT
  args:
    image_size: 224
    patch_size: 32
    num_classes: 100
    dim: 512 # TODO: Smaller?
    depth: 3 # TODO: Smaller?
    heads: 4 # TODO: Smaller?
    mlp_dim: 1024 # TODO: Smaller?
    dropout: 0.1

teacher_optimizer:
  type: SGD 
  args:
    lr: 0.01

student_optimizer:
  type: SGD 
  args:
    lr: 0.01